### ISSUE TITLE
Include date of deadline together with countdown

### ISSUE THREAD

**Issue by petrusmatiros** [Hampfh/DataLinks#42]
Would be nice to have the date of said assignments together with the countdown and not just the countdown. It could be an option or it could be the default 

One example:

Assignment

<Course name> Uppsats period 1

2021-09-09 18:00

1 Week(s)

18:15:30

**Comment by Hampfh** [comment]
That's a good suggestion, I'll see what I can do to make it work in the UI

**Comment by Hampfh** [comment]
This feature has now been implemented and pushed to the site
